import { useMantineColorScheme } from '@mantine/core'
import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import AboutSection from '../components/index/AboutSection'
import ContactSection from '../components/index/ContactSection'
import ExperienceSection from '../components/index/ExperienceSection'
import HeroSection from '../components/index/HeroSection'
import WorkSection from '../components/index/WorkSection'
import PaddedContainer from '../components/layout/PaddedContainer'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

interface Props {

}

const Home: NextPage<Props> = ({ }: Props) => {

  return (
    <>
      <Head>
        <title>Sebastian Schuler: Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PaddedContainer>

        <HeroSection />
        <AboutSection />
        <ExperienceSection />
        <WorkSection />
        <ContactSection />

      </PaddedContainer>

    </>
  )
}

export const getStaticProps: GetStaticProps = async ({ locale }) => {


  return {
    props: {
      ...(await serverSideTranslations(locale || "en", ['common', 'index'])),
    },
  };
}

export default Home
