import { Container } from '@mantine/core'
import type { GetStaticProps, NextPage } from 'next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import Head from 'next/head'
import AboutSection from '../ui/index/about-section'
import ExperienceSection from '../ui/index/experience-section'
import HeroSection from '../ui/index/hero-section'
import WorkSection from '../ui/index/work-section'

interface Props {

}

const Home: NextPage<Props> = ({ }: Props) => {

  return (
    <>
      <Head>
        <title>Sebastian Schuler: Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>

        <HeroSection />
        <AboutSection />
        <ExperienceSection />
        <WorkSection />

      </Container>

    </>
  )
}

export const getStaticProps: GetStaticProps = async ({ locale }) => {


  return {
    props: {
      ...(await serverSideTranslations(locale || "en", ['common', 'index'])),
    },
  };
}

export default Home
